#app_path - Admyself Application server path
#encoding_app_key - This key is matched with booking app key before it start the encoding. If it doesn't match then encoding script will not run

#log - Logger info file path

#temp_file_path - It is a temporary directory for the temporary convertion files are stored, before encode/upload to s3
#tvc_path - total video converter executable path.  Its used to convert the downloaded files to flv
#flv_ini_file_path - total video converter ini file path

#curl_path - curl executable path. It is used to download and upload files
#recipients - Recipients mail address for Exception information

--- 

app_path: http://admyself.railsfactory.com
encoding_app_key: 986978ff42278c4b93db7c9fbfa252f40f508fee

s3path: http://s3.amazonaws.com/digital-production/mediafiles
s3path_filler: http://s3.amazonaws.com/digital-production/filler_videos
bucket_name: digital-production


log: D:/Railsfactory/projects/encoder/log/encoding_log.txt
#log: /home/railsfactory/projects/encoding/log/encoding_log.txt

temp_file_path: D:\\Railsfactory\\projects\\encoder\\temp
tvc_path: c:/Program Files/Total Video Converter/tvc
flv_ini_file_path: c:\\Program Files\\Total Video Converter\\ini\\flv.ini


curl_path: c:/curl-7.18.0
recipients: vadivelan@railsfactory.org , saravanankrishnan@railsfactory.org

