#db_host  database server name 
#db_username - database username
#db_password  - database password
#db_name  - database name 
#db_port  - database port name 

#access_key_id - Amazon s3 access key file id
#secret_access_key - Amazon s3 secret access key
#bucket_name - s3's Bucket Name 
#s3server_url - amazon s3 server url
#action_path - Exact url of available files

#log - Logger info file path
#temp_file_path - its a temp directory for the temporary convertion files are stored, before encode/upload to s3
#tvc_path - total video converter executable path.  Its used to convert the downloaded files to flv
#flv_ini_file_path - total video converter ini file path

#curl_path - curl executable path. It is used to download and upload files
#recipients - Recipients mail address for Exception information

--- 


db_host: 127.0.0.1
db_username: root
db_password: 
db_name: digital_development
db_port:

access_key_id: 1V2CH6DZ6FJMCTZ06TR2
secret_access_key: 61SxYAOuwBAmX9SkZh2CStxo7MH1ODe8tRJdR+sH
s3server_url: s3.amazonaws.com
action_path: /digital-production/mediafiles

s3path: http://s3.amazonaws.com/digital-production/mediafiles
bucket_name: digital-production


log: d:/projects/encoding/log/encoding_log.txt
temp_file_path: d:/projects/encoding/temp
flv_ini_file_path: c:/Program Files/Total Video Converter/ini/flv.ini
tvc_path: c:/Program Files/Total Video Converter/tvc

curl_path: c:/curl-7.18.0
recipients: shivsingh@railsfactory.org , saravanankrishnan@railsfactory.org